use crate::ast::{BinaryOp, Expr, ExprX, Ral, RalEntry};
use std::collections::HashMap;
use std::fmt::Write;

fn eval_const(expr: &Expr, defines: &HashMap<String, u64>) -> Option<u64> {
    match &**expr {
        ExprX::Num(n) => Some(*n as u64),
        ExprX::Var(v) => defines.get(v.as_str()).copied(),
        ExprX::Binary(op, l, r) => {
            let l_val = eval_const(&l.x, defines)?;
            let r_val = eval_const(&r.x, defines)?;
            match op {
                BinaryOp::Add => Some(l_val.wrapping_add(r_val)),
                BinaryOp::Subtract => Some(l_val.wrapping_sub(r_val)),
            }
        }
    }
}

fn render_expr(expr: &Expr, defines: &HashMap<String, u64>) -> String {
    if let Some(v) = eval_const(expr, defines) {
        return v.to_string();
    }
    match &**expr {
        ExprX::Num(n) => n.to_string(),
        ExprX::Var(v) => v.to_string(),
        ExprX::Binary(op, l, r) => {
            let op_str = match op {
                BinaryOp::Add => "+",
                BinaryOp::Subtract => "-",
            };
            format!(
                "({} {} {})",
                render_expr(&l.x, defines),
                op_str,
                render_expr(&r.x, defines)
            )
        }
    }
}

fn round_up_width(bits: u64) -> u32 {
    match bits {
        0..=8 => 8,
        9..=16 => 16,
        17..=32 => 32,
        _ => 64,
    }
}

fn c_int_type(width: u32) -> &'static str {
    match width {
        8 => "uint8_t",
        16 => "uint16_t",
        32 => "uint32_t",
        _ => "uint64_t",
    }
}

fn c_lit_suffix(width: u32) -> &'static str {
    match width {
        32 => "U",
        64 => "ULL",
        _ => "",
    }
}

fn build_offset(offset_const: u64, offset_dynamic: &[String]) -> String {
    if offset_dynamic.is_empty() {
        return offset_const.to_string();
    }
    let mut parts: Vec<String> = offset_dynamic.to_vec();
    if offset_const > 0 {
        parts.push(offset_const.to_string());
    }
    parts.join(" + ")
}

fn mask_literal(size_expr: &Expr, defines: &HashMap<String, u64>, suffix: &str) -> String {
    if let Some(size) = eval_const(size_expr, defines) {
        let mask_val = if size >= 64 {
            u64::MAX
        } else {
            (1u64 << size) - 1
        };
        format!("0x{:x}{}", mask_val, suffix)
    } else {
        let size_str = render_expr(size_expr, defines);
        format!("((1{} << ({})) - 1)", suffix, size_str)
    }
}

pub fn convert_to_c(ral: Ral, defines: &HashMap<String, u64>) -> String {
    let mut out = String::new();
    out.push_str("// Generated by ral. Do not edit.\n");
    out.push_str("#pragma once\n");
    out.push_str("#include <stdint.h>\n\n");

    for (reg_name, entry) in &ral.registers {
        let RalEntry::RawRegister(reg_spanned) = entry else {
            continue;
        };
        let reg = &reg_spanned.x;

        let reg_bits = eval_const(&reg.size.x, defines).unwrap_or(64);
        let width = round_up_width(reg_bits);
        let int_type = c_int_type(width);
        let suffix = c_lit_suffix(width);

        let mut offset_const: u64 = 0;
        let mut offset_dynamic: Vec<String> = Vec::new();

        for field in reg.fields.iter().rev() {
            let offset_str = build_offset(offset_const, &offset_dynamic);
            let mask_str = mask_literal(&field.size.x, defines, suffix);

            if let Some(field_name_spanned) = &field.name {
                let field_name = &field_name_spanned.x;

                // Getter
                let _ = writeln!(
                    out,
                    "static inline {ty} {reg}_{f}_get({ty} val) {{",
                    ty = int_type,
                    reg = reg_name,
                    f = field_name,
                );
                if offset_str == "0" {
                    let _ = writeln!(out, "    return val & {};", mask_str);
                } else {
                    let _ = writeln!(out, "    return (val >> {}) & {};", offset_str, mask_str);
                }
                out.push_str("}\n\n");

                // Setter
                let _ = writeln!(
                    out,
                    "static inline {ty} {reg}_{f}_set({ty} val, {ty} field_val) {{",
                    ty = int_type,
                    reg = reg_name,
                    f = field_name,
                );
                if offset_str == "0" {
                    let _ = writeln!(
                        out,
                        "    return (val & ~{m}) | (field_val & {m});",
                        m = mask_str
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "    return (val & ~({m} << {o})) | ((field_val & {m}) << {o});",
                        m = mask_str,
                        o = offset_str,
                    );
                }
                out.push_str("}\n\n");
            }

            // Update offset state for the next (more-significant) field.
            if let Some(n) = eval_const(&field.size.x, defines) {
                offset_const += n;
            } else {
                offset_dynamic.push(render_expr(&field.size.x, defines));
            }
        }
    }

    out
}
