use crate::ast::{BinaryOp, Expr, ExprX, Ral, RalEntry};
use std::collections::HashMap;
use std::fmt::Write;

fn eval_const(expr: &Expr, defines: &HashMap<String, u64>) -> Option<u64> {
    match &**expr {
        ExprX::Num(n) => Some(*n as u64),
        ExprX::Var(v) => defines.get(v.as_str()).copied(),
        ExprX::Binary(op, l, r) => {
            let l_val = eval_const(&l.x, defines)?;
            let r_val = eval_const(&r.x, defines)?;
            match op {
                BinaryOp::Add => Some(l_val.wrapping_add(r_val)),
                BinaryOp::Subtract => Some(l_val.wrapping_sub(r_val)),
            }
        }
    }
}

fn render_expr(expr: &Expr, defines: &HashMap<String, u64>) -> String {
    if let Some(v) = eval_const(expr, defines) {
        return v.to_string();
    }
    match &**expr {
        ExprX::Num(n) => n.to_string(),
        ExprX::Var(v) => v.to_string(),
        ExprX::Binary(op, l, r) => {
            let op_str = match op {
                BinaryOp::Add => "+",
                BinaryOp::Subtract => "-",
            };
            format!(
                "({} {} {})",
                render_expr(&l.x, defines),
                op_str,
                render_expr(&r.x, defines)
            )
        }
    }
}

fn round_up_width(bits: u64) -> u32 {
    match bits {
        0..=8 => 8,
        9..=16 => 16,
        17..=32 => 32,
        _ => 64,
    }
}

fn rust_int_type(width: u32) -> &'static str {
    match width {
        8 => "u8",
        16 => "u16",
        32 => "u32",
        _ => "u64",
    }
}

fn snake_to_pascal(s: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' {
            capitalize_next = true;
            continue;
        }
        if capitalize_next {
            for u in c.to_uppercase() {
                out.push(u);
            }
            capitalize_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn build_offset(offset_const: u64, offset_dynamic: &[String]) -> String {
    if offset_dynamic.is_empty() {
        return offset_const.to_string();
    }
    let mut parts: Vec<String> = offset_dynamic.to_vec();
    if offset_const > 0 {
        parts.push(offset_const.to_string());
    }
    parts.join(" + ")
}

fn mask_literal(size_expr: &Expr, defines: &HashMap<String, u64>) -> String {
    if let Some(size) = eval_const(size_expr, defines) {
        let mask_val = if size >= 64 {
            u64::MAX
        } else {
            (1u64 << size) - 1
        };
        format!("0x{:x}", mask_val)
    } else {
        let size_str = render_expr(size_expr, defines);
        format!("((1 << ({})) - 1)", size_str)
    }
}

pub fn convert_to_rust(ral: Ral, defines: &HashMap<String, u64>) -> String {
    let mut out = String::new();
    out.push_str("// Generated by ral. Do not edit.\n");
    out.push_str("#![allow(dead_code)]\n");

    for (reg_name, entry) in &ral.registers {
        let RalEntry::RawRegister(reg_spanned) = entry else {
            continue;
        };
        let reg = &reg_spanned.x;
        let struct_name = snake_to_pascal(reg_name);

        let reg_bits = eval_const(&reg.size.x, defines).unwrap_or(64);
        let width = round_up_width(reg_bits);
        let int_type = rust_int_type(width);

        out.push('\n');
        let _ = writeln!(out, "#[repr(transparent)]");
        let _ = writeln!(
            out,
            "#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]"
        );
        let _ = writeln!(out, "pub struct {}(pub {});", struct_name, int_type);
        out.push('\n');
        let _ = writeln!(out, "impl {} {{", struct_name);
        let _ = writeln!(out, "    #[inline]");
        let _ = writeln!(
            out,
            "    pub const fn new(val: {}) -> Self {{ Self(val) }}",
            int_type
        );
        out.push('\n');
        let _ = writeln!(out, "    #[inline]");
        let _ = writeln!(
            out,
            "    pub const fn raw(self) -> {} {{ self.0 }}",
            int_type
        );

        let mut offset_const: u64 = 0;
        let mut offset_dynamic: Vec<String> = Vec::new();

        for field in reg.fields.iter().rev() {
            let offset_str = build_offset(offset_const, &offset_dynamic);
            let mask_str = mask_literal(&field.size.x, defines);

            if let Some(field_name_spanned) = &field.name {
                let field_name = &field_name_spanned.x;

                // Getter: `fn <name>(self) -> T`
                out.push('\n');
                let _ = writeln!(out, "    #[inline]");
                let _ = writeln!(
                    out,
                    "    pub const fn {}(self) -> {} {{",
                    field_name, int_type
                );
                if offset_str == "0" {
                    let _ = writeln!(out, "        self.0 & {}", mask_str);
                } else {
                    let _ = writeln!(
                        out,
                        "        (self.0 >> {}) & {}",
                        offset_str, mask_str
                    );
                }
                let _ = writeln!(out, "    }}");

                // Setter: `fn with_<name>(self, field_val: T) -> Self`
                out.push('\n');
                let _ = writeln!(out, "    #[inline]");
                let _ = writeln!(
                    out,
                    "    pub const fn with_{}(self, field_val: {}) -> Self {{",
                    field_name, int_type
                );
                if offset_str == "0" {
                    let _ = writeln!(
                        out,
                        "        Self((self.0 & !{m}) | (field_val & {m}))",
                        m = mask_str
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "        Self((self.0 & !({m} << {o})) | ((field_val & {m}) << {o}))",
                        m = mask_str,
                        o = offset_str,
                    );
                }
                let _ = writeln!(out, "    }}");
            }

            if let Some(n) = eval_const(&field.size.x, defines) {
                offset_const += n;
            } else {
                offset_dynamic.push(render_expr(&field.size.x, defines));
            }
        }

        let _ = writeln!(out, "}}");
    }

    out
}
